DROP DATABASE IF EXISTS restdb;
DROP USER IF EXISTS ´restadmin´@´%´;
CREATE DATABASE IF NOT EXISTS restdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'restadmin'@'%' IDENTIFIED BY mysql_native_password BY 'password';
GRANT SElECT, INSERT, UPDATE, DELETE CREATE, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE,EVENT, TRIGGER ON ´restdb´.* TO 'restadmin'@'%';